enabled: true
log_debug: false

com.beepboop.app.MainApp:
  level: DEBUG
  enabled: true

com.beepboop.app.dataprovider.DataImporter:
  level: DEBUG
  enabled: true


com.beepboop.app.dataprovider.SolutionParser:
  level: DEBUG
  enabled: true

com.beepboop.app.ge_interpreter.AStarPhenotypeGenerator:
  level: DEBUG
  enabled: false

com.beepboop.app.mutations.MutationEngine:
  level: INFO
  enabled: true


com.beepboop.app.mutations.Mutation:
  level: DEBUG
  enabled: true

com.beepboop.app.mutations.ReplaceOperator:
  level: DEBUG
  enabled: false

com.beepboop.app.mutations.ExpressionGenerator:
  level: WARN
  enabled: false


com.beepboop.app.mutations.ReplaceSubtree:
  level: DEBUG
  enabled: false


com.beepboop.app.dataprovider.ModelParser:
  level: DEBUG
  enabled: true

com.beepboop.app.dataprovider.DataProvider:
  level: INFO
  enabled: true

com.beepboop.app.dataprovider.DataProvider$VarRegistry:
  level: DEBUG
  enabled: true


com.beepboop.app.dataprovider.DataProvider$ParameterRegistry:
  level: DEBUG
  enabled: true


com.beepboop.app.components.BinaryExpression:
  level: DEBUG
  enabled: false

com.beepboop.app.components.SumExpression:
  level: DEBUG
  enabled: true

com.beepboop.app.astar.AStar:
  level: INFO
  enabled: true

com.beepboop.app.dataprovider.PersistenceManager:
  level: DEBUG
  enabled: true

com.beepboop.app.components.ComponentRegistry:
  level: DEBUG
  enabled: true

com.beepboop.app.postprocessor.JoinConstants:
  level: DEBUG
  enabled: false

com.beepboop.app.cpicker.Runner:
  level: INFO
  enabled: true


com.beepboop.app.cpicker.ConstraintPicker:
  level: INFO
  enabled: true
